require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'KLTN' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'react-native-speech-to-text', :path => '../node_modules/react-native-google-speech-to-text'

  target 'KLTNTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'KLTN-tvOS' do
  # Pods for KLTN-tvOS

  target 'KLTN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
